### ISSUE TITLE
Construct Binary Tree from Inorder and Postorder 

### ISSUE THREAD

**Issue by Arihant1467** [DivyaGodayal/CoderChef-Kitchen#103]
[Contruct Tree from Inorder Traversal and Postorder Traversal](https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/)

This might be a tricky interview question where you are asked to generate preorder traversal from given inorder and postorder traversals.

**Comment by DivyaGodayal** [comment]
Awesome ! You can go ahead with the writing the article.
Once you are done, link you PR to this issue. Have a great one 💯👍

**Comment by Arihant1467** [comment]
Pull request:  #105
