### ISSUE TITLE
Generate Parentheses

### ISSUE THREAD

**Issue by Arihant1467** [DivyaGodayal/CoderChef-Kitchen#98]
###  [Generate Parentheses](https://leetcode.com/problems/generate-parentheses)

This question will help students about how to draw and solve problems using recursion tree whenever they encounter such permutations based questions

**Comment by edorado93** [comment]
Sounds good @Arihant1467. Go ahead with the article 👍 
Once you're done creating a PR, link it to this issue by mentioning the PR number here in a comment like e.g. 

```
#97
```

**Comment by Arihant1467** [comment]
I am done making the pull request. Please have a look at it and let me know if any changes are needed to be done from my side.
Pulll Request : #99

**Comment by edorado93** [comment]
Hey Arihant,
Thank you for the PR. I will look into it and get back to you. You can
assign it to me for now.

**Comment by edorado93** [comment]
#99

**Comment by Arihant1467** [comment]
Thank you Sachin for accepting my contribution. Your edits made it a very
good article.

Thank you.
Arihant Sai

**Comment by edorado93** [comment]
👍 
Looking forward to many more contributions from you!
